CREATE TABLE AGENDA(
	CODIGO 		INT AUTO_INCREMENT PRIMARY KEY,
    NOME 		VARCHAR(50) NOT NULL,
    TELEFONE 	CHAR(11) NOT NULL,
    INSTAGRAM 	VARCHAR(30),
    ENDERECO 	VARCHAR(50),
    EMAIL 		VARCHAR(50)
    );